language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saivasi96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saivasi96/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react-1"
  env: "Dockerreact1-env"
  bucket_name: "elasticbeanstalk-us-east-1-377220503076"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
